name: Build maria-backup
on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
    paths:
    - 'maria-backup/**/*'

jobs:
  kaniko:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Kaniko build
        uses: aevea/action-kaniko@master
        with:
          image: nhillsdonuk/maria-backup
          username: ${{ secrets.DHUB_USER }}
          password: ${{ secrets.DHUB_TOKEN }}
          build_file: "maria-backup/Dockerfile"
          tag: "latest"
