name: Build Rubocop-lax
on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
    paths:
    - 'rubocop-cicd/lax/*'
    - 'rubocop-cicd/rubocop-lax'

jobs:
  kaniko:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Kaniko build
        uses: aevea/action-kaniko@master
        with:
          image: nhillsdonuk/rubocop-cicd
          username: ${{ secrets.DHUB_USER }}
          password: ${{ secrets.DHUB_TOKEN }}
          build_file: "rubocop-cicd/rubocop-lax"
          tag: 3.1.2-lax
          strip_tag_prefix: true
